jobs:
  - job: Init
    pool:
        name: rdo-backup-prod
        vmImage: Ubuntu-18.04

    steps:
    - task: CopyFiles@1
      displayName: Copy files
      inputs:
        contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
        cleanTargetFolder: true

    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        addSpnToEnvironment: True
        azureSubscription: Netbox
        scriptType: bash
        scriptLocation: 'scriptPath'
        scriptPath: get_vnets.sh
        workingDirectory: $(Build.ArtifactStagingDirectory)