jobs:
  - job: Populate_Netbox
    pool:
        name: rdo-backup-prod
        vmImage: Ubuntu-18.04

    steps:
    - task: CopyFiles@1
      displayName: Copy files
      inputs:
        contents: '**'
        TargetFolder: $(Build.ArtifactStagingDirectory)
        cleanTargetFolder: true

    # - task: Bash@3
    #   displayName: Bash script
    #   inputs:
    #     targetType: inline
    #     workingDirectory: $(System.DefaultWorkingDirectory)
    #     script: ./get_vnets.sh

    - task: AzureCLI@2
      displayName: Azure CLI
      inputs:
        azureSubscription: Netbox
        workingDirectory: $(Build.ArtifactStagingDirectory)
        scriptLocation: inlineScript
        addSpnToEnvironment: true
        failOnStandardError: 'true'
        scriptType: bash
        inlineScript: |   
          echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query="id" -o tsv)"
          echo "##vso[task.setvariable variable=ARM_TENANT_ID]$(az account show --query="tenantId" -o tsv)"
          echo '##vso[task.setvariable variable=ARM_CLIENT_ID;isOutput=true]$(ARM_CLIENT_ID)'
          echo '##vso[task.setvariable variable=ARM_CLIENT_SECRET;isOutput=true]$(ARM_CLIENT_SECRET)'

    - task: ShellScript@2
      displayName: 'Bootstrap Configure AKS'
      inputs:
        scriptPath: get_vnets.sh
        #args: '${{ parameters.project }} ${{ parameters.serviceBootstrap }} ${{ parameters.environment }} ${{ parameters.keyVaultName }} ${{ parameters.subscriptionName }} "${{ parameters.command }}" '
        failOnStderr: true

    - task: PythonScript@0
      displayName: Populate Netbox with Azure Prefixes
      inputs:
        scriptSource: 'filePath'
        scriptPath: netbox.py
        arguments: --ENVIRONMENT ${{ parameters.environment }} --KEY_VAULT_NAME $(KEY_VAULT_NAME) --AZURE_TENANT_ID $(AZURE_TENANT_ID) --AZURE_CLIENT_ID $(AZURE_CLIENT_ID) --AZURE_CLIENT_SECRET $(AZURE_CLIENT_SECRET)
        workingDirectory: $(Build.ArtifactStagingDirectory)