jobs:
  - job: Populate_Netbox
    pool:
        name: rdo-backup-prod
        vmImage: Ubuntu-18.04

    steps:

    - task: DownloadPipelineArtifact@1
      inputs:
        source: 'current'
        artifact: 'drop'
        path: '$(System.DefaultWorkingDirectory)/drop'

    - task: PythonScript@0
      displayName: Populate Netbox with Azure Prefixes
      inputs:
        scriptSource: 'filePath'
        scriptPath: netbox.py
        arguments: --ENVIRONMENT ${{ parameters.environment }} --KEY_VAULT_NAME $(KEY_VAULT_NAME) --AZURE_TENANT_ID $(AZURE_TENANT_ID) --AZURE_CLIENT_ID $(AZURE_CLIENT_ID) --AZURE_CLIENT_SECRET $(AZURE_CLIENT_SECRET)
        workingDirectory: $(Build.ArtifactStagingDirectory)