jobs:
  - job: Populate_Netbox
    pool:
        name: hmcts-cftptl-agent-pool
        vmImage: Ubuntu-18.04

    steps:

    - task: DownloadPipelineArtifact@1
      inputs:
        source: 'current'
        artifact: 'drop'
        path: '$(Build.ArtifactStagingDirectory)'

    - task: PythonScript@0
      displayName: Populate Netbox with Azure Prefixes
      inputs:
        scriptSource: 'filePath'
        scriptPath: $(Build.ArtifactStagingDirectory)/drop/netbox.py
        arguments: --ENVIRONMENT ${{ parameters.environment }} --KEY_VAULT_NAME $(KEY_VAULT_NAME)-${{ parameters.environment }} --AZURE_TENANT_ID $(AZURE_TENANT_ID) --AZURE_CLIENT_ID $(AZURE_CLIENT_ID) --AZURE_CLIENT_SECRET $(AZURE_CLIENT_SECRET)
        workingDirectory: $(Build.ArtifactStagingDirectory)/drop/
