jobs:
  - job: Populate_Netbox
    pool:
        name: rdo-backup-prod
        vmImage: Ubuntu-18.04

    steps:

    - task: DownloadPipelineArtifact@1
      inputs:
        source: 'current'
        artifact: 'drop'
        path: '$(Build.ArtifactStagingDirectory)'

    - task: PythonScript@0
      displayName: Populate Netbox with Azure Prefixes
      inputs:
        azureSubscription: HMCTS-HUB-${{ parameters.subenv }}-INTSVC
          workingDirectory: $(Build.ArtifactStagingDirectory)/drop/
          scriptType: bash
          scriptLocation: inlineScript
          inlineScript: |
            #!/bin/bash
            set -e
            client_id="$(az keyvault secret show --name client-id --vault-name netbox-vault-${{ parameters.environment }} --query value --output tsv)"
            client_secret="$(az keyvault secret show --name client-secret --vault-name netbox-vault-${{ parameters.environment }} --query value --output tsv)"
            python $(Build.ArtifactStagingDirectory)/drop/scripts/netbox.py --ENVIRONMENT ${{ parameters.environment }} --KEY_VAULT_NAME netbox-vault-${{ parameters.environment }} --AZURE_TENANT_ID ${{ parameters.tenantId }} --AZURE_CLIENT_ID $client_id --AZURE_CLIENT_SECRET $client_secret
