jobs:
  - job: Populate_Netbox
    pool:
      name: hmcts-cftptl-agent-pool
      vmImage: Ubuntu-18.04

    steps:
      - task: DownloadPipelineArtifact@1
        inputs:
          source: "current"
          artifact: "drop"
          path: "$(Build.ArtifactStagingDirectory)"

      - task: Bash@3
        displayName: Populate Netbox with Azure Prefixes
        inputs:
          filePath: ./python3-deploy.sh
          arguements: netbox.py
          workingDirectory: $(Build.ArtifactStagingDirectory)/drop
