repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.80.0
    hooks:
      - id: terraform_fmt
        verbose: true
      - id: terraform_docs
        args:
          - --args=--config=.terraform-docs.yml
          - --hook-config=--path-to-file=README.md