trigger:
- master

pr:
- master

stages:

############################### STAGING ############################### 

- stage: netbox_stg
  displayName: Netbox Staging
  jobs:
  - template: pipeline-templates/deploy.yaml
    parameters:
      environment: 'stg'

############################### PROD ############################### 

- stage: netbox_prod
  displayName: Netbox Prod
  dependsOn: netbox_stg
  condition: succeeded('netbox_stg')
  jobs:
  - template: pipeline-templates/deploy.yaml
    parameters:
      environment: 'prod'
