name: chart netbox pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    ref: endakelly-patch-1
    endpoint: 'hmcts'

jobs:
- job: Validate
  # Make sure we have a tag to run this job
 
  pool:
    name: hmcts-sandbox-agent-pool
  steps:
  - template: steps/charts/validate.yaml@cnp-library
    parameters:
      chartName: netbox
      chartReleaseName: netbox-ci-test
      chartNamespace: netbox
      acrName: "hmctspublic"
      chartPath: "./charts/"
      valuesFile: "./charts/netbox/ci-values.yaml"
      businessArea: ss
      environment: ptlsbox

- job: Release
  # Make sure we have a tag to run this job
  condition: startsWith(variables['Build.SourceBranch'], 'refs/tags/')
 
  pool:
    name: hmcts-sandbox-agent-pool
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: netbox
      chartReleaseName: netbox-ci-test
      chartNamespace: netbox
      acrName: "hmctspublic"
      chartPath: "./charts/"
      valuesFile: "./charts/netbox/ci-values.yaml"
      environment: ss-ptlsbox
