name: chart netbox pipeline
trigger:
  branches:
    include:
    - refs/tags/*
pr:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: cnp-library
    type: github
    name: hmcts/cnp-azuredevops-libraries
    endpoint: 'hmcts (1)'

jobs:
- job: Release
  # Make sure we have a tag to run this job
  condition: >
    and(
        succeeded(),
        startsWith(variables['Build.SourceBranch'], 'refs/tags/')
      )
 
  pool:
    name: hmcts-sandbox-agent-pool
  steps:
  - template: steps/charts/release.yaml@cnp-library
    parameters:
      chartName: netbox
      chartReleaseName: netbox-ci-test
      chartNamespace: chart-tests
      serviceConnection: "DCD-CFTAPPS-SBOX"
      aksResourceGroup: "cft-sbox-00-rg"
      aksCluster: "cft-sbox-00-aks"
      acrName: "sdshmctspublic"
      chartPath: "./charts/"
