trigger:
  - master
  

pr:
  - master

stages:
  ############################### PTLSBOX ###############################

  - stage: init_ptlsbox
    displayName: Init Sbox
    jobs:
      - template: pipeline-templates/copy_files.yaml
        parameters:
          agentPool: "hmcts-sds-ptlsbox"

  - stage: netbox_sbox
    displayName: Netbox Sbox
    dependsOn: init_ptlsbox
    condition: succeeded('init_ptlsbox')
    jobs:
      - template: pipeline-templates/deploy.yaml
        parameters:
          environment: "ptlsbox"
          tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
          agentPool: "hmcts-sds-ptlsbox"

  ############################### PROD ###############################

  - stage: init_ptl
    displayName: Init Prod
    dependsOn: netbox_sbox
    jobs:
      - template: pipeline-templates/copy_files.yaml
        parameters:
          agentPool: "hmcts-sds-ptl"

  - stage: netbox_prod
    displayName: Netbox Prod
    dependsOn: init_ptl
    condition: and(succeeded('netbox_sbox'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipeline-templates/deploy.yaml
        parameters:
          environment: "ptl"
          tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
          agentPool: "hmcts-sds-ptl"
