trigger:
  - master

pr:
  - master

stages:
  ############################### STAGING ###############################

  # - stage: netbox_stg
  #   displayName: Netbox Staging
  #   dependsOn: init
  #   condition: succeeded('init')
  #   jobs:
  #   - template: pipeline-templates/deploy.yaml
  #     parameters:
  #       environment: 'stg'
  #       tenantId: '531ff96d-0ae9-462a-8d2d-bec7c0b42082'

  ############################### PTLSBOX ###############################

  - stage: init_ptlsbox
    displayName: Init
    jobs:
      - template: pipeline-templates/copy_files.yaml
        parameters:
          agentPool: "hmcts-sds-ptlsbox"

  - stage: netbox_sbox
    displayName: Netbox Sbox
    dependsOn: init_ptlsbox
    condition: succeeded('init_ptlsbox')
    jobs:
      - template: pipeline-templates/deploy.yaml
        parameters:
          environment: "ptlsbox"
          tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
          agentPool: "hmcts-sds-ptl"

  ############################### PROD ###############################

  - stage: init_ptl
    displayName: Init
    dependsOn: netbox_ptlsbox
    jobs:
      - template: pipeline-templates/copy_files.yaml
        parameters:
          agentPool: "hmcts-sds-ptlsbox"

  - stage: netbox_prod
    displayName: Netbox Prod
    dependsOn: init_ptl
    condition: and(succeeded('netbox_ptlsbox'), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    jobs:
      - template: pipeline-templates/deploy.yaml
        parameters:
          environment: "prod"
          tenantId: "531ff96d-0ae9-462a-8d2d-bec7c0b42082"
          agentPool: "hmcts-sds-ptl"
