apiVersion: v1
kind: Service
metadata:
  name: {{ include "netbox.fullname" . }}
  labels:
{{ include "netbox.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "netbox.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  {{ if .Values.service.loadBalancerSourceRanges -}}
  loadBalancerSourceRanges:
    {{ toYaml .Values.service.loadBalancerSourceRanges | indent 4 | trim }}
  {{- end }}
